#!/bin/bash
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64
chmod +x manifest-tool

# Apply to latest
./manifest-tool push from-spec multi-arch-manifest.yaml

# Apply to concrete version
TAG_SPLIT="$(cut -d'-' -f1 <<<"$DOCKER_TAG")"
sed "s/TAGNAME/${TAG_SPLIT}/g" multi-arch-manifest.template.yaml > multi-arch-manifest-tag.yaml
./manifest-tool push from-spec multi-arch-manifest-tag.yaml
rm -f multi-arch-manifest-tag.yaml